name: release_binaries
on:
  release:
    types: created

jobs:
  macOS:
    name: Add macOS binaries to release
    runs-on: macOS-latest
    env:
      XCODE_VERSION: ${{ '14.1.0' }}
    steps:
      - name: Select Xcode
        run: "sudo xcode-select -s /Applications/Xcode_$XCODE_VERSION.app"
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set tag name
        run: echo "TAG_NAME=$(echo $GITHUB_REF | cut -c 11-)" >> $GITHUB_ENV
      - name: Build arm64-apple-macosx
        run: "swift build -c release --triple arm64-apple-macosx"
      - name: Zip arm64-apple-macosx release
        run: "mkdir releases && zip -j releases/XCMetrics-macOS-arm64-$TAG_NAME.zip .build/release/xcmetrics"
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: releases/*
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
